services:
  hextrackr:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./data:/app/data
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
