services:
  hextrackr:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"
    volumes:
      # Mount source files for development but exclude node_modules
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
