services:
  # Main StackTrackr Application
  stacktrackr-app:
    build:
      context: .
      target: stacktrackr-app
    ports:
      - "4033:3000"  # Changed from 3033 to 4033 to avoid conflicts
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - rengine-network
    restart: unless-stopped
    command: ["npm", "run", "dev"]

  # rEngine Platform Services
  rengine-platform:
    build:
      context: .
      target: rengine-services
    ports:
      - "4034:8080"  # Changed to 4034 for consistency
      - "4035:8081"  # Changed to 4035 for consistency
    volumes:
      - ./rEngine:/rengine
      - ./rAgents:/rengine/rAgents
      - ./rMemory:/rengine/rMemory
      - ./logs:/rengine/logs
    environment:
      - NODE_ENV=development
      - MCP_SERVER_URL=http://mcp-server:8082
    depends_on:
      - mcp-server
    networks:
      - rengine-network
    restart: unless-stopped
    command: ["nodemon", "index.js"]

  # MCP Memory Server
  mcp-server:
    build:
      context: .
      target: mcp-server
    ports:
      - "4036:8082"  # Changed to 4036 for consistency
    volumes:
      - ./rMemory:/data
      - ./rEngineMCP:/mcp
      - /mcp/node_modules
    environment:
      - NODE_ENV=development
      - DATA_PATH=/data
    networks:
      - rengine-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development Environment (VS Code Server)
  development:
    build:
      context: .
      target: development
    ports:
      - "4037:8000"  # Changed to 4037 for consistency
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker if needed
    environment:
      - NODE_ENV=development
    networks:
      - rengine-network
    command: ["sleep", "infinity"]

  # nginx Reverse Proxy (for production-like setup)
  nginx:
    image: nginx:alpine
    ports:
      - "4032:80"   # Changed to 4032 (your requested starting port)
      - "4038:443"  # Changed to 4038 for consistency
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
    depends_on:
      - stacktrackr-app
      - rengine-platform
    networks:
      - rengine-network
    restart: unless-stopped

networks:
  rengine-network:
    driver: bridge

volumes:
  node_modules:
  mcp_data:
